#if defined _akrp_feature_loader_included
    #endinput
#endif
#define _akrp_feature_loader_included

// AKRP V5 feature modules. Keep this order: it mirrors the old monolith compile order.
#include "modules/akrp/core/runtime_state.pwn"
#include "modules/akrp/core/entrypoints_and_location.pwn"
#include "modules/akrp/systems/core_services.pwn"
#include "modules/akrp/systems/domain_helpers.pwn"
#include "modules/akrp/database/model_callbacks.pwn"
#include "modules/akrp/database/query_dispatcher.pwn"
#include "modules/akrp/server/gamemode_lifecycle.pwn"
#include "modules/akrp/identity/player_connection.pwn"
#include "modules/akrp/ui/player_spawn_textdraws.pwn"
#include "modules/akrp/server/gameplay_callbacks.pwn"
#include "modules/akrp/dialogs/responses.pwn"
#include "modules/akrp/identity/roleplay_identity_commands.pwn"
#include "modules/akrp/vehicles/vehicle_controls_and_phone.pwn"
#include "modules/akrp/player/help_economy_reports.pwn"
#include "modules/akrp/player/acceptance_and_discord_link.pwn"
#include "modules/akrp/integrations/discord_player_commands.pwn"
#include "modules/akrp/admin/admin_help_and_moderation.pwn"
#include "modules/akrp/admin/admin_powers_and_vehicles.pwn"
#include "modules/akrp/admin/events_and_world_admin.pwn"
#include "modules/akrp/properties/dynamic_world_admin.pwn"
#include "modules/akrp/properties/housing_business_robbery.pwn"
#include "modules/akrp/staff/staff_and_property_services.pwn"
#include "modules/akrp/properties/doors_garages_businesses.pwn"
#include "modules/akrp/jobs/jobs_bank_mechanic_phone.pwn"
#include "modules/akrp/communications/phone_sms_radio.pwn"
#include "modules/akrp/player/settings_help_animation_identity.pwn"
#include "modules/akrp/vehicles/ownership_and_jobs.pwn"
#include "modules/akrp/vip/vip_blackmarket.pwn"
#include "modules/akrp/factions/faction_law_medic_news.pwn"
#include "modules/akrp/gangs/gangs_turfs_points.pwn"
#include "modules/akrp/misc/misc_commands_and_anticheat.pwn"
#include "modules/akrp/seasonal/hacker_voice_carol.pwn"
#include "modules/akrp/integrations/discord_staff_commands.pwn"
